src/AltV.Net/Elements/Entities/IVehicle.cs, src/AltV.Net/Elements/Entities/Vehicle.cs, src/AltV.Net/Enums/VehicleLockState.cs, src/AltV.Net/Native/AltV.Vehicle.cs
=> Vehicle Lockstate Enum

api/AltV.Net.Async/AltAsync.Vehicle.cs
=> Added CreateVehicle() with string parameter

api/AltV.Net.Async/AsyncEntityPool.cs
Example with a hash that doesn't exist:
await AltAsync.CreateVehicle(0x0203223, Position.Zero, 0);
=> Fixed zero pointer entity creation

api/AltV.Net/Alt.Blip.cs, api/AltV.Net/Alt.Checkpoint.cs, api/AltV.Net/Alt.ColShape.cs
=> Added documentation of Blip, Checkpoint and ColShape.

api/AltV.Net.Host/Host.cs
=> Use strong reference to keep ResourceAssemblyLoadContext alive until ExecuteResourceUnload gets called

api/AltV.Net/Elements/Entities/IVoiceChannel.cs
Add documentation to IVoiceChannel interface
=> Add comments (#82)

api/AltV.Net/Elements/Entities/ICheckpoint.cs
Add documentation to ICheckpoint interface
=> Add comments (#81)

api/AltV.Net/Elements/Entities/IColShape.cs
Fixes documentation so that the descriptions are correct
=> #80 IColShape Interface

api/AltV.Net/Enums/WeaponModel.cs
I've updated some weapon hashes to their correct values.
=> Update outdated WeaponModel hashes

api/AltV.Net/Enums/VehicleModType.cs
I've found WindowTint works for slot 69, also added DashboardColor & TrimColor
=> Updated VehicleModType

docs/articles/player_death.md
event that will called after player death.
=> player_death.md

docs/articles/player_damage.md
=> player_damage.md

api/AltV.Net/Data/Position.cs, api/AltV.Net/Data/ReadOnlyPlayer.cs, api/AltV.Net/Elements/Entities/BaseObject.cs, api/AltV.Net/Elements/Entities/IBaseObject.cs
* Fixes loop reference in "Normalized"  without introducing depency to Newtonsoft.Json
* Introduce BaseObject.GetAllData() to retrieve all available data-Keys
=> Attribute "Position" as Datacontract / Introduce BaseObject.GetAllData

api/AltV.Net.Client/Alt.cs, api/AltV.Net.Client/NativeAlt.cs, api/AltV.Net.WebAssembly.Example/Program.cs
Added the functions that were missing for the AltV client namespace from the documentation
WIP, because setWeatherCycle throws RuntimeError: memory access out of bounds
=> WIP: Add missing AltV client functions

api/AltV.Net.Client/Alt.cs, api/AltV.Net.Client/Elements/Entities/HandlingData.cs, api/AltV.Net.Client/Elements/Entities/IHandlingData.cs, api/AltV.Net.Client/NativeHandlingData.cs, api/AltV.Net.WebAssembly.Example/Program.cs, webassembly-example/dotnet-runtime-dependencies/resource.cfg, webassembly-example/dotnet-runtime/dotnet.js
Added HandlingData Class to clientside
Tested getters with cars, motorcycles and airplanes
=> Add HandlingData to clientside

api/AltV.Net.Client/Elements/Entities/IDiscordUser.cs
=> IDiscordUser.cs

api/AltV.Net.Async/AltAsync.Player.cs, api/AltV.Net.Async/AltAsync.Vehicle.cs
change SetRoofOpenAsync to SetRoofOpenedAsync to match property
=> Add missing async setters

api/AltV.Net.Async/AltAsync.Entity.cs, api/AltV.Net.Async/Elements/Entities/VehicleBuilder.cs, api/AltV.Net.Async/IVehicleBuilder.cs
Add missing Asyncs
Get/SetStreamSyncedMetaData
Aprearance + Script Data in IVehicleBuilder
=> Add missing Asyncs

docs/articles/player_death.md
IPlayer Killer  => IEntity entity.
=> Updated PlayerDeath

docs/articles/player_enter_vehicle.md, docs/articles/player_leave_vehicle.md
=> Added PlayerEnterVehicle & PlayerLeftVehicle to our Wiki.

api/AltV.Net/FunctionParser/FunctionObjectParsers.cs
=> Improve object parsers

api/AltV.Net.Async/AltAsync.RegisterEvents.cs, api/AltV.Net.Async/AltAsync.cs, api/AltV.Net.Async/AsyncModule.cs, api/AltV.Net.Async/Events/Events.cs, api/AltV.Net/Alt.Events.cs, api/AltV.Net/Alt.RegisterEvents.cs, api/AltV.Net/CSharpResourceImpl.cs, api/AltV.Net/Events/Events.cs, api/AltV.Net/Module.cs, api/AltV.Net/ModuleWrapper.cs, api/AltV.Net/Native/AltV.Resource.cs, api/AltV.Net/ScriptEventType.cs, runtime/include/CSharpResourceImpl.h, runtime/src/CSharpResourceImpl.cpp
Added `OnPlayerEnteringVehicle` event which triggers just when the player tries to enter a vehicle.
=> Added OnPlayerEnteringVehicle event

api/AltV.Net/Elements/Entities/IPlayer.cs, api/AltV.Net/Elements/Entities/Player.cs, api/AltV.Net/IServer.cs, api/AltV.Net/Native/AltV.Player.cs, api/AltV.Net/Native/AltV.Server.cs, api/AltV.Net/Server.cs, runtime/src/altv-c-api/player.cpp, runtime/src/altv-c-api/player.h, runtime/src/altv-c-api/server.cpp, runtime/src/altv-c-api/server.h
Adds `ICore::SetPassword` and `IPlayer::IsEntityInStreamingRange`
=> Add missing stuff

api/AltV.Net/Data/Cloth.cs, api/AltV.Net/Data/DlcCloth.cs, api/AltV.Net/Data/DlcProp.cs, api/AltV.Net/Data/Prop.cs, api/AltV.Net/Elements/Entities/IPlayer.cs, api/AltV.Net/Elements/Entities/Player.cs, api/AltV.Net/Native/AltV.Player.cs, runtime/src/altv-c-api/cloth.h, runtime/src/altv-c-api/dlc_cloth.h, runtime/src/altv-c-api/dlc_prop.h, runtime/src/altv-c-api/player.cpp, runtime/src/altv-c-api/player.h, runtime/src/altv-c-api/prop.h
- `IPlayer::GetClothes`
- `IPlayer::SetClothes`
- `IPlayer::GetDlcClothes`
- `IPlayer::SetDlcClothes`
- `IPlayer::GetProps`
- `IPlayer::SetProps`
- `IPlayer::GetDlcProps`
- `IPlayer::SetDlcProps`
=> Add clothes and props

api/AltV.Net/Elements/Entities/IEntity.cs, api/AltV.Net/Elements/Entities/Player.cs, api/AltV.Net/Elements/Entities/Vehicle.cs, api/AltV.Net/Native/AltV.Player.cs, api/AltV.Net/Native/AltV.Vehicle.cs, runtime/src/altv-c-api/player.cpp, runtime/src/altv-c-api/player.h, runtime/src/altv-c-api/vehicle.cpp, runtime/src/altv-c-api/vehicle.h
**This still needs to be tested, I do not have the tools set up to compile and test the C# module**
=> Add AttachToEntity and Detach to IEntity

api/AltV.Net.Async/AltAsync.Player.cs, api/AltV.Net.Async/AltAsync.RegisterEvents.cs, api/AltV.Net.Async/AltAsync.Vehicle.cs, api/AltV.Net.Async/AltAsync.cs, api/AltV.Net.Async/AsyncModule.cs, api/AltV.Net.Async/Events/Events.cs, api/AltV.Net/Alt.Events.cs, api/AltV.Net/Alt.RegisterEvents.cs, api/AltV.Net/CSharpResourceImpl.cs, api/AltV.Net/Elements/Entities/Entity.cs, api/AltV.Net/Elements/Entities/IEntity.cs, api/AltV.Net/Elements/Entities/Player.cs, api/AltV.Net/Elements/Entities/Vehicle.cs, api/AltV.Net/Events/Events.cs, api/AltV.Net/Module.cs, api/AltV.Net/ModuleWrapper.cs, api/AltV.Net/Native/AltV.Resource.cs, api/AltV.Net/Native/Library.cs, api/AltV.Net/ScriptEventType.cs, runtime/include/CSharpResourceImpl.h, runtime/src/CSharpResourceImpl.cpp, runtime/src/altv-c-api/player.cpp, runtime/src/altv-c-api/player.h, runtime/src/altv-c-api/vehicle.cpp, runtime/src/altv-c-api/vehicle.h
Streamed
Visibile
OnVehicleDamage
=> Added Streamed, Visible & OnVehicleDamage

api/AltV.Net.Async/AltAsync.Player.cs, api/AltV.Net.Async/AltAsync.Vehicle.cs
- Added IVehicle.AttachToEntityAsync
- Added IVehicle.AttachedAsync
- Added IVehicle.AttachedToAsync
- Added IVehicle.DetachAsync
- Added IVehicle.DoesWheelHasTireAsync
- Added IVehicle.GetArmoredWindowHealthAsync
- Added IVehicle.GetArmoredWindowShootCountAsync
- Added IVehicle.GetBumperDamageLevelAsync
- Added IVehicle.GetBumperDamageLevelExtAsync
- Added IVehicle.GetLightsMultiplierAsync
- Added IVehicle.GetLiveryAsync
- Added IVehicle.GetPartBulletHolesAsync
- Added IVehicle.GetPartBulletHolesExtAsync
- Added IVehicle.GetPartDamageLevelAsync
- Added IVehicle.GetPartDamageLevelExtAsync
- Added IVehicle.GetRearWheelAsync
- Added IVehicle.GetRoofLiveryAsync
- Added IVehicle.GetWheelHealthAsync
- Added IVehicle.IsDestroyedAsync
- Added IVehicle.IsLightDamagedAsync
- Added …
=> Added setters & getter to async

api/AltV.Net.Async/AltAsync.Player.cs, api/AltV.Net.Mock/MockServer.cs, api/AltV.Net/Alt.cs, api/AltV.Net/Elements/Entities/IPlayer.cs, api/AltV.Net/Elements/Entities/Player.cs, api/AltV.Net/IServer.cs, api/AltV.Net/Native/Library.cs, api/AltV.Net/Server.cs, runtime/src/altv-c-api/player.cpp, runtime/src/altv-c-api/player.h, runtime/src/altv-c-api/server.cpp, runtime/src/altv-c-api/server.h
`IPlayer.Invincible { get; set; }`
`Alt.EmitClients(IEnumerable<IPlayer> clients, string eventName, params object[] args)`
=> IPlayer.Invincible & Alt.EmitClients

api/AltV.Net.EntitySync.Entities/AltV.Net.EntitySync.Entities.csproj
Enables source link for EntitySync.Entities to improve debugger experience for visual studio and rider.
=> Enable source link for entitiysync.entities

api/AltV.Net.EntitySync/IEntity.cs
Makes range setter available outside of the module.
=> Make IEntity Range settable

api/AltV.Net.Resources.Chat.Api/AltV.Net.Resources.Chat.Api.csproj
Enables source link to improve debugger experience.
=> Enable source link in AltV.Net.Resources.Chat.Api

api/AltV.Net.VehicleData/AltV.Net.VehicleData.csproj
Improves debugger experience for AltV.Net.VehicleData module.
=> Add Source link support to AltV.Net.VehicleData
